export function mapReactor1(values = {}) {
  return {
    Temperature: values.Temperature,
    SetTemperature: values.SetTemperature,
    ColumnTemperature: values.ColumnTemperature,
    ColumnSetTemperature: values.ColumnSetTemperature,
    HeatExchangerOutTemperature: values.HeatExchangerOutTemperature,
    Pressure: values.Pressure,
    HotOilInletTemperature: values.HotOilInletTemperature,
    HotOilOutletTemperature: values.HotOilOutletTemperature,
    HotOilFlowmeter: values.HotOilFlowmeter,
    HotOilFrequence: values.HotOilFrequence,
    TransferPumpRPM: values.TransferPumpRPM,
    TransferPumpCurrent: values.TransferPumpCurrent,
    MixerRPM: values.MixerRPM,
    MixerCurrent: values.MixerCurrent,
    Cooling3WayValveRatio: values.Cooling3WayValveRatio,
    Heating3WayValveRatio: values.Heating3WayValveRatio,
    VacuumPumpMaxRatio: values.VacuumPumpMaxRatio,
    AlcoholFlowmeter: values.AlcoholFlowmeter,
    ProcessLevel: values.ProcessLevel,
    ColorHeating: values.ColorHeating,
    ColorMixer: values.ColorMixer,
    ColorVacuum: values.ColorVacuum,
    ColorHotOilPump: values.ColorHotOilPump,
    ColorColumnCoolingPump: values.ColorColumnCoolingPump,
    ColorFirstSeperator: values.ColorFirstSeperator,
    ColorSecondSeperator: values.ColorSecondSeperator,
    ColorAlcoholValve: values.ColorAlcoholValve,
    ColorTransferPump: values.ColorTransferPump,
    ColorFault: values.ColorFault,
  };
}
